name: test react-native

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: yarn
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
      - name: install react-native lib dependencies
        run: yarn install
        working-directory: react/netbird-lib
      - name: run npm prepack
        run: npm run prepack
        working-directory: react/netbird-lib
      - name: add react-native lib
        run: yarn add file:./react/netbird-lib
      - name: yarn install deps
        run: yarn install
      - name: npx reacti-native bundle
        run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: create empty local.properties
        run: touch android/local.properties
      - name: run npm tests
        run: npm test
